# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='sss',
        ),
        migrations.AddField(
            model_name='meal',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
