# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170407_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
