# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_meal_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Meal')),
            ],
        ),
    ]
