# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mealbydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
            ],
        ),
    ]
