# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_activedates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedates',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
