# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170408_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='menu_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
