# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_menu_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
