# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cartmeals_meal_qnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='meals_qnt',
            field=models.IntegerField(null=True),
        ),
    ]
