# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-13 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170413_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ad_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
