# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170414_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.DeleteModel(
            name='CartStatus',
        ),
    ]
