# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170414_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealimage',
            name='image_350_350',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\catering/main/static/images/meals'),
        ),
    ]
