# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_ingredients_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
