# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20170417_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedates',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
