# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_activedates_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealForComplexMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_246_246', models.ImageField(blank=True, null=True, upload_to='D:\\projects\\catering/main/static/images/menu')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ComplexMenu')),
            ],
        ),
    ]
