# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-22 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_complexmenu_mealforcomplexmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexMenuByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealforcomplexmenu',
            name='image_246_246',
        ),
        migrations.AddField(
            model_name='complexmenu',
            name='image_246_246',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\catering/main/static/images/menu'),
        ),
        migrations.AddField(
            model_name='complexmenu',
            name='menu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MenuType'),
        ),
        migrations.AddField(
            model_name='complexmenubydate',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ComplexMenu'),
        ),
    ]
