# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_complexmenu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
