# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_complexmenu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealforcomplexmenu',
            name='qnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
