# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_mealforcomplexmenu_qnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexmenu',
            name='date',
        ),
    ]
