# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_complexmenu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexmenubydate',
            name='menu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MenuType'),
        ),
    ]
