# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_mealforcomplexmenu_menu_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmeals',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ComplexMenu'),
        ),
    ]
