# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-27 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20170426_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cultery',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
