# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-27 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_cart_cultery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cultery',
            new_name='cutlery',
        ),
    ]
