# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20170707_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
