# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceGreyOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Icon')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place')),
            ],
        ),
    ]
