# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-20 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20170720_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeoption',
            name='infrastructure_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.InfrastructureItem'),
        ),
        migrations.AlterField(
            model_name='placeoption',
            name='option',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='placeoption',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
    ]
