# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-20 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20170720_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructureitem',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
