# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-20 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_placeimage_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='infrastructure_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.InfrastructureItem'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
    ]
