# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20170720_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeoption',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
