# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-20 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_placeoption_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='main_image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
