# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-21 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_place_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringClientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place')),
            ],
        ),
    ]
