# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-21 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_cateringclientrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CateringClientRequest',
            new_name='PlaceClientRequest',
        ),
    ]
