# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-21 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_placeclientrequest_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceClientRequest',
            new_name='ClientRequest',
        ),
    ]
