# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-21 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20170721_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.OrderStatus'),
        ),
    ]
