# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-22 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_tag_tagplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=2000, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
