# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_testimonial_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
