# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_portfolioitem_portfolioitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitemimage',
            name='main_foto',
            field=models.BooleanField(default=False),
        ),
    ]
