# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-25 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_portfolioitemimage_main_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitemimage',
            old_name='main_foto',
            new_name='main_image',
        ),
    ]
