# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-31 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20170725_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='D:\\projects\\catering/main/static/images/staff')),
                ('image_name', models.CharField(max_length=150)),
            ],
        ),
    ]
