# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-31 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
