# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-31 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20170731_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
