# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20170731_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='index',
            field=models.BooleanField(default=False),
        ),
    ]
