# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-31 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20170731_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='name',
        ),
    ]
