# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-07 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PortfolioItem'),
        ),
    ]
