# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20170807_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='index',
            field=models.BooleanField(default=False),
        ),
    ]
