# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_portfolioitem_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='slider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
