# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20170808_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitemimage',
            name='image_watermark',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\catering/main/static/images/portfolio/watermark'),
        ),
    ]
