# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_portfolioitemimage_image_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitemimage',
            name='name_watermark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
