# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-09 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_portfolioitemimage_name_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='image_watermark',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\catering/main/static/images/places/watermark/'),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='name_watermark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
