# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-11 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_phonenumber_placecontactperson_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecontactperson',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placecontactperson',
            name='ad_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='placecontactperson',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
        migrations.AlterField(
            model_name='placecontactperson',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
