# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-11 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_auto_20170811_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placecontactperson',
            name='user',
        ),
    ]
