# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-11 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_remove_placecontactperson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecontactperson',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='placecontactperson',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
